<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-T134AMI" name="com.index.AddCartIndex" tests="6" failures="0" timestamp="25 Aug 2021 10:47:09 GMT" time="41.569" errors="1">
  <testcase name="login_blankPassword" time="3.495" classname="com.index.AddCartIndex">
    <skipped/>
  </testcase> <!-- login_blankPassword -->
  <testcase name="init" time="3.735" classname="com.index.AddCartIndex">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.index.LoginIndex.init(LoginIndex.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- init -->
  <testcase name="login" time="27.629" classname="com.index.AddCartIndex">
    <skipped/>
  </testcase> <!-- login -->
  <testcase name="addProductToCart" time="2.577" classname="com.index.AddCartIndex">
    <skipped/>
  </testcase> <!-- addProductToCart -->
  <testcase name="login_negative" time="4.133" classname="com.index.AddCartIndex">
    <skipped/>
  </testcase> <!-- login_negative -->
  <testcase name="login_blankUserName" time="0.000" classname="com.index.AddCartIndex">
    <skipped/>
  </testcase> <!-- login_blankUserName -->
</testsuite> <!-- com.index.AddCartIndex -->
